name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Build Flutter Web
        run: |
          cd frontend
          flutter build web --release --base-href "/Menu_project_New/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
